import fs from 'node:fs'
import path from 'node:path'
import type { PromptBlock } from '../../prompts'
import type { LocalCommandRecord } from '../commands/registry'

const MAX_CLAUDE_MD_CHARS = 200_000

export function buildClaudeMdInjectedBlocks(args: { cwd: string }): PromptBlock[] {
  const cwd = args.cwd
  const filePath = path.join(cwd, 'CLAUDE.md')
  if (!fs.existsSync(filePath)) return []

  let contents = ''
  try {
    contents = fs.readFileSync(filePath, 'utf8')
  } catch {
    return []
  }

  const truncated = contents.length > MAX_CLAUDE_MD_CHARS
  if (truncated) contents = contents.slice(0, MAX_CLAUDE_MD_CHARS) + '\n\n(Truncated)\n'

  const text =
    '<system-reminder>\n' +
    "As you answer the user's questions, you can use the following context:\n" +
    '# claudeMd\n' +
    'Codebase and user instructions are shown below. Be sure to adhere to these instructions. ' +
    'IMPORTANT: These instructions OVERRIDE any default behavior and you MUST follow them exactly as written.\n\n' +
    `Contents of ${filePath} (project instructions, checked into the codebase):\n\n` +
    contents +
    '\n\n' +
    'IMPORTANT: this context may or may not be relevant to your tasks. ' +
    'You should not respond to this context unless it is highly relevant to your task.\n' +
    '</system-reminder>\n'

  return [{ type: 'text', text, cache_control: { type: 'ephemeral' } }]
}

export function buildLocalCommandInjectedBlocks(rec: LocalCommandRecord): PromptBlock[] {
  return [
    {
      type: 'text',
      text:
        'Caveat: The messages below were generated by the user while running local commands. ' +
        'DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.',
      cache_control: { type: 'ephemeral' },
    },
    {
      type: 'text',
      text:
        `<command-name>${rec.commandName}</command-name>\n` +
        `            <command-message>${rec.commandMessage}</command-message>\n` +
        `            <command-args>${rec.commandArgs}</command-args>`,
      cache_control: { type: 'ephemeral' },
    },
    {
      type: 'text',
      text: `<local-command-stdout>${rec.stdout}</local-command-stdout>`,
      cache_control: { type: 'ephemeral' },
    },
  ]
}
