export type ReactiveCompactErrorKind =
  | 'http_413'
  | 'request_too_large'
  | 'input_too_long'
  | 'prompt_too_long'
  | 'maximum_context_length'
  | 'context_length_exceeded'
  | 'context_limit'
  | 'too_many_tokens'
  | 'reduce_messages_length'
